feat(about): Guide Native_install_version_14_and_upgrade_15
eclipse/sw360.website pull request #16
Opened 2022-07-08 01:48 UTC by tuannn2

Sw360 installation documents without docker version 14 and update to version 15

2022-07-08 04:46 UTC, KoukiHama requested changes
Basically,  ok
about the sw360.property,  please use these setting to be more general description, 
https://github.com/eclipse/sw360/blob/sw360-14.0.0-M1/backend/src-common/src/main/resources/sw360.properties

2022-07-08 04:46 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Native-Install-Version-14.0.0-and-Upgrade-Version-15.0.0.md
> +        sw360changelog.config.file.location=/opt/sw360logs
This is not default setting. 

#Uncomment the below file location if the log4j2.xml file is placed inside etc/sw360 folder.
#sw360changelog.config.file.location=/etc/sw360/log4j2.xml


https://github.com/eclipse/sw360/blob/63a1fa6211e97c39b84f60676804aa3cc83e0f2d/backend/src-common/src/main/resources/sw360.properties#L77-L80

2022-07-08 04:46 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Native-Install-Version-14.0.0-and-Upgrade-Version-15.0.0.md
> +        backend.timeout.read = 6000000
This is not default setting, and need not mention here.

2022-07-08 04:46 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Native-Install-Version-14.0.0-and-Upgrade-Version-15.0.0.md
> +        backend.timeout.connection = 50000
This is not default setting, and need not mention here.

2022-07-08 13:05 UTC, heliocastro requested changes
It's ok, but i suggest two possible changes:
- Move to legacy, as is based on very old non supoprted anymore Ubuntu 18.04 OR
- Prepare the guide with Ubuntu 22.04

I'll be ok to merge like this and then move to 22.04

2022-07-09 12:37 UTC, KoukiHama commented
and mark down should be split to" install 14 version page" and "upgrade from 14 to 15"
As Helio mentioned, "install 14 version" should be in https://github.com/eclipse/sw360.website/tree/master/content/en/docs/Deployment/Legacy

2022-07-12 02:10 UTC, tuannn2 commented
> It's ok, but i suggest two possible changes:
> 
> * Move to legacy, as is based on very old non supoprted anymore Ubuntu 18.04 OR
> * Prepare the guide with Ubuntu 22.04
> 
> I'll be ok to merge like this and then move to 22.04

2022-07-12 02:13 UTC, tuannn2 commented
Thank you for your review, @KoukiHama @heliocastro. I will change according to your comments!

2022-07-12 04:39 UTC, tuannn2 commented
hi @heliocastro, 

-  I have updated the 14 installation md file, from ubuntu 18 to 20. Please check it!
-  I am preparing and testing SW360 on ubuntu 22.04.

2022-07-12 04:41 UTC, tuannn2 commented
hi @KoukiHama.  I split the md file into 2 install 14 and updated to 15. Please check it!

2022-07-12 05:28 UTC, KoukiHama approved these changes

2022-07-12 05:28 UTC, KoukiHama commented
@tuannn2  Thank you! It is OK for me now.

2022-07-20 23:04 UTC, merged